### PR TITLE
Create 2_script_manual_tmp.sh

### PR DESCRIPTION
**Pull request by thomsonOZ**
Updated distfeeds.conf to 21.02.0 release so can pass the installation.

### CODE REVIEW

**Comment by ihrapsa** [comment]
Thanks! Could you commit only the modifications you made so I can just merge with the main? maybe if you keep the original filename Github will figure it out by itself

**Comment by thomsonOZ** [comment]
I added distfeeds from line 72 to 93
Comment out #131/132 as 21.02.0 also need skip signature check

**Review by thomsonOZ — COMMENTED** [review]
Updated script, first time updated change in Github

**Comment by ihrapsa** [comment]
All good. Thanks!

**Pull request merged**
